import { EventLogger } from "./event-logger";

// Types
export type { DemoEvent, DemoAnalytics, FallbackReason, PerformanceMetrics, DemoEventInput, AutoGeneratedFields } from "./types";

// Utility functions
export { isValidEvent, generateEventId, getSessionId, parseEvent, validateAndTransformEvent } from "./utils";

// Constants
export { FALLBACK_CONSTANTS, FALLBACK_MESSAGES, PERFORMANCE_CONSTANTS } from "./constants";

// Event logger instance
export const eventLogger = EventLogger.getInstance();

// Public utility functions
export function getDemoEvents() {
    return eventLogger.getStoredEvents();
}

export function clearDemoEvents() {
    return eventLogger.clearEvents();
}

export function getEventStats() {
    return eventLogger.getEventStats();
}
