import { EventLogger } from "./event-logger";
import type { DemoMode } from "../config";

// Types
export type { DemoEvent, DemoAnalytics, FallbackReason, PerformanceMetrics, DemoEventInput, AutoGeneratedFields } from "./types";

// Utility functions
export { isValidEvent, generateEventId, getSessionId, parseEvent, validateAndTransformEvent } from "./utils";

// Constants
export { FALLBACK_CONSTANTS, FALLBACK_MESSAGES, PERFORMANCE_CONSTANTS } from "./constants";

// Event logger instance
export const eventLogger = EventLogger.getInstance();

// Public utility functions
export function getDemoEvents() {
    return eventLogger.getStoredEvents();
}

export function clearDemoEvents() {
    return eventLogger.clearEvents();
}

export function getEventStats() {
    return eventLogger.getEventStats();
}

// Analytics tracking methods
export function trackDemoView(slug: string, mode: DemoMode) {
    return eventLogger.trackDemoView(slug, mode);
}

export function trackDemoSuccess(slug: string, mode: DemoMode, duration: number) {
    return eventLogger.trackDemoSuccess(slug, mode, duration);
}
